# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabwidget2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabwidget2.setGeometry(QtCore.QRect(0, -1, 1651, 751))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(11)
        self.tabwidget2.setFont(font)
        self.tabwidget2.setObjectName("tabwidget2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 661, 701))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 57, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.dial = QtWidgets.QDial(self.groupBox)
        self.dial.setGeometry(QtCore.QRect(200, 20, 141, 91))
        self.dial.setMinimum(1)
        self.dial.setMaximum(4000)
        self.dial.setSingleStep(200)
        self.dial.setObjectName("dial")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setGeometry(QtCore.QRect(420, 30, 191, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.dial_2 = QtWidgets.QDial(self.groupBox)
        self.dial_2.setGeometry(QtCore.QRect(210, 130, 131, 91))
        self.dial_2.setMinimum(1)
        self.dial_2.setMaximum(4000)
        self.dial_2.setSingleStep(200)
        self.dial_2.setObjectName("dial_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(420, 150, 191, 71))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 290, 221, 21))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(3000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(420, 270, 191, 71))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(170, 410, 221, 21))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(30)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(420, 390, 191, 71))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(60, 540, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 540, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 540, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 20, 461, 691))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(100, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(120, 100, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(15)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(50, 220, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(50, 270, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(50, 320, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(50, 370, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 200, 86, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdb1_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb1_start.setFont(font)
        self.rdb1_start.setObjectName("rdb1_start")
        self.verticalLayout.addWidget(self.rdb1_start)
        self.rdb2_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb2_start.setFont(font)
        self.rdb2_start.setObjectName("rdb2_start")
        self.verticalLayout.addWidget(self.rdb2_start)
        self.rdb3_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb3_start.setFont(font)
        self.rdb3_start.setObjectName("rdb3_start")
        self.verticalLayout.addWidget(self.rdb3_start)
        self.rdb4_start = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb4_start.setFont(font)
        self.rdb4_start.setObjectName("rdb4_start")
        self.verticalLayout.addWidget(self.rdb4_start)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(320, 200, 86, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rdb1_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb1_end.setFont(font)
        self.rdb1_end.setObjectName("rdb1_end")
        self.verticalLayout_2.addWidget(self.rdb1_end)
        self.rdb2_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb2_end.setFont(font)
        self.rdb2_end.setObjectName("rdb2_end")
        self.verticalLayout_2.addWidget(self.rdb2_end)
        self.rdb3_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb3_end.setFont(font)
        self.rdb3_end.setObjectName("rdb3_end")
        self.verticalLayout_2.addWidget(self.rdb3_end)
        self.rdb4_end = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rdb4_end.setFont(font)
        self.rdb4_end.setObjectName("rdb4_end")
        self.verticalLayout_2.addWidget(self.rdb4_end)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(171, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(310, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.rdb_exec = QtWidgets.QPushButton(self.groupBox_2)
        self.rdb_exec.setGeometry(QtCore.QRect(80, 450, 101, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdb_exec.setFont(font)
        self.rdb_exec.setObjectName("rdb_exec")
        self.rdb_clean = QtWidgets.QPushButton(self.groupBox_2)
        self.rdb_clean.setGeometry(QtCore.QRect(260, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdb_clean.setFont(font)
        self.rdb_clean.setObjectName("rdb_clean")
        self.rdc_absorb = QtWidgets.QPushButton(self.groupBox_2)
        self.rdc_absorb.setGeometry(QtCore.QRect(80, 530, 111, 41))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.rdc_absorb.setFont(font)
        self.rdc_absorb.setObjectName("rdc_absorb")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(190, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setGeometry(QtCore.QRect(320, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setMaximum(16)
        self.spinBox_3.setObjectName("spinBox_3")
        self.tabwidget2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Data_look = QtWidgets.QPushButton(self.tab_2)
        self.Data_look.setGeometry(QtCore.QRect(500, 100, 101, 41))
        self.Data_look.setObjectName("Data_look")
        self.Data_R_search = QtWidgets.QPushButton(self.tab_2)
        self.Data_R_search.setGeometry(QtCore.QRect(200, 180, 151, 41))
        self.Data_R_search.setObjectName("Data_R_search")
        self.Data_N_search = QtWidgets.QPushButton(self.tab_2)
        self.Data_N_search.setGeometry(QtCore.QRect(200, 240, 151, 41))
        self.Data_N_search.setObjectName("Data_N_search")
        self.Data_reaction = QtWidgets.QPushButton(self.tab_2)
        self.Data_reaction.setGeometry(QtCore.QRect(580, 180, 171, 41))
        self.Data_reaction.setObjectName("Data_reaction")
        self.Datatable = QtWidgets.QTableWidget(self.tab_2)
        self.Datatable.setGeometry(QtCore.QRect(50, 330, 1021, 271))
        self.Datatable.setObjectName("Datatable")
        self.Datatable.setColumnCount(0)
        self.Datatable.setRowCount(0)
        self.Data_R_tx = QtWidgets.QLineEdit(self.tab_2)
        self.Data_R_tx.setGeometry(QtCore.QRect(370, 180, 141, 41))
        self.Data_R_tx.setToolTip("")
        self.Data_R_tx.setObjectName("Data_R_tx")
        self.Data_N_tv = QtWidgets.QLineEdit(self.tab_2)
        self.Data_N_tv.setGeometry(QtCore.QRect(370, 240, 141, 41))
        self.Data_N_tv.setObjectName("Data_N_tv")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(760, 180, 131, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.tabwidget2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.exec_spec = QtWidgets.QPushButton(self.tab_3)
        self.exec_spec.setGeometry(QtCore.QRect(80, 60, 131, 61))
        self.exec_spec.setObjectName("exec_spec")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(80, 190, 961, 491))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("G:/图库/11-17-01-90-7.jpg"))
        self.label_13.setObjectName("label_13")
        self.tabwidget2.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabwidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabwidget2.setToolTip(_translate("MainWindow", "<html><head/><body><p>光谱分许</p></body></html>"))
        self.tabwidget2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "指令发送"))
        self.label.setText(_translate("MainWindow", "抽取速度"))
        self.label_2.setText(_translate("MainWindow", "排出速度"))
        self.label_3.setText(_translate("MainWindow", "抽取体积"))
        self.label_4.setText(_translate("MainWindow", "循环次数"))
        self.pushButton.setText(_translate("MainWindow", "初始化"))
        self.pushButton_2.setText(_translate("MainWindow", "停止"))
        self.pushButton_3.setText(_translate("MainWindow", "执行"))
        self.groupBox_2.setTitle(_translate("MainWindow", "泵切换与端口控制"))
        self.label_5.setText(_translate("MainWindow", "泵编号"))
        self.label_6.setText(_translate("MainWindow", "泵端口号"))
        self.label_7.setText(_translate("MainWindow", "蠕动泵1"))
        self.label_8.setText(_translate("MainWindow", "蠕动泵2"))
        self.label_9.setText(_translate("MainWindow", "蠕动泵3"))
        self.label_10.setText(_translate("MainWindow", "蠕动泵4"))
        self.label_11.setText(_translate("MainWindow", "开始时间(s)"))
        self.label_12.setText(_translate("MainWindow", "结束时间(s)"))
        self.rdb_exec.setText(_translate("MainWindow", "执行"))
        self.rdb_clean.setText(_translate("MainWindow", "清洗"))
        self.rdc_absorb.setText(_translate("MainWindow", "测吸收基线"))
        self.label_14.setText(_translate("MainWindow", "蠕动泵端口号"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab), _translate("MainWindow", "手动调试"))
        self.Data_look.setText(_translate("MainWindow", "查看数据库"))
        self.Data_R_search.setText(_translate("MainWindow", "按反应物查找数据"))
        self.Data_N_search.setText(_translate("MainWindow", "按编号查找数据"))
        self.Data_reaction.setText(_translate("MainWindow", "执行反应（按编号）"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>按编号</p></body></html>"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_2), _translate("MainWindow", "数据库"))
        self.exec_spec.setText(_translate("MainWindow", "光谱图"))
        self.tabwidget2.setTabText(self.tabwidget2.indexOf(self.tab_3), _translate("MainWindow", "光谱分析"))

